receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  batch:
exporters:
  logging:
    logLevel: debug
  datadog/api:
    api:
      key: ${DD_API_KEY}

service:
  pipelines:
    traces:
      receivers:
      - otlp
      processors:
      - batch
      exporters:
      - logging
      - datadog/api